sudo: required
language: node_js
node_js:
  - "8.11.1"

env:
  - TRAVIS=true DEBUG="froq-*" DEBUG_COLORS=1

services:
  - docker

before_install:
  - npm install -g lerna

install:
  - lerna bootstrap

script:
  - lerna run test